apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-server
  name: hello-server
spec:
  clusterIP: 10.163.240.101
  ports:
    - name: grpc
      port: 7900
      targetPort: 7900
    - name: debug
      port: 7901
      targetPort: 7901
  selector:
    name: hello-server
