apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-server
spec:
  replicas: 1
  selector:
    name: hello-server
  template:
    metadata:
      labels:
        name: hello-server
    spec:
      containers:
      - name: hello-server
        image: kelseyhightower/hello-server:1.0.0
        command:
          - "/hello-server"
        args:
          - "-listen-addr=0.0.0.0:7900"
          - "-debug-listen-addr=0.0.0.0:7901"
          - "-ca-cert=/tls/ca.pem"
          - "-tls-key=/tls/key.pem"
          - "-tls-cert=/tls/cert.pem"
          - "-jwt-public-key=/tls/jwt.pem"
        ports:
          - name: grpc
            containerPort: 7900
          - name: debug
            containerPort: 7901
        resources:
          limits:
            cpu: 0.2
            memory: "100Mi"
        volumeMounts:
          - name: "hello-server-tls"
            readOnly: true
            mountPath: "/tls"
      volumes:
        - name: "hello-server-tls"
          secret:
            secretName: "hello-server-tls"
